import * as Privacy from '../privacy';
import * as Judge from '../judge';
const day=24*60*60*1000;
test('defaultListIsOnAndEverythingElseOff',()=>{for(const p of ['com.twitter.android','com.linkedin.android','com.google.android.gm','com.whatsapp'])expect(Privacy.allowed(p,null)).toBe(true);for(const p of ['org.thoughtcrime.securesms','com.android.chrome','dev.ownvoice.app'])expect(Privacy.allowed(p,null)).toBe(false);});
test('userChoiceWins',()=>{expect(Privacy.allowed('org.thoughtcrime.securesms',true)).toBe(true);expect(Privacy.allowed('com.whatsapp',false)).toBe(false);});
test('readsOlderThan30DaysAreDropped',()=>{const now=100*day;const reads=[0,now-31*day,now-30*day,now-30*day+1,now-day,now].map(time=>({time,app:'a',label:'A',summary:'s'}));expect(Privacy.keep(reads,now).map(r=>r.time)).toEqual([now-30*day+1,now-day,now]);});
test('summarySaysWhatItDidButNeverTheText',()=>{const chat='Sam: Are we still on for Saturday?\nSam: I can bring the tent.';expect(Privacy.summary('REPLY',chat,'')).toBe('Suggested replies. Read the chat on screen.');expect(Privacy.summary('COMPOSE',chat,'Saturday works')).toBe('Polished your message. Read the chat on screen and your message.');expect(Privacy.summary('EMPTY','','')).toBe('Nothing to help with. Nothing was on screen.');});
test('oldEntriesReadInPlainWords',()=>{expect(Privacy.plain('Compose boost. 0 characters on screen, 14 in your field.')).toBe('Polished your message. Read your message.');expect(Privacy.plain('Reply drafts. 117 characters on screen, 0 in your field.')).toBe('Suggested replies. Read the chat on screen.');expect(Privacy.plain('Suggested replies. Read the chat on screen.')).toBe('Suggested replies. Read the chat on screen.');});
test('readSurvivesEncodingAndTabsCannotBreakIt',()=>{const read={time:42,app:'com.android.chrome',label:'Chrome',summary:'a\tb\nc'};expect(Privacy.decode(Privacy.encode(read))).toEqual({...read,summary:'a b c'});expect(Privacy.decode('garbage')).toBeNull();expect(Privacy.decode('')).toBeNull();});
