import {RewriteEngine,Version,versionsList,versions,clean,rewrite,rewritePrompt,versionPrompt} from '../judge';
test('readsTheVersions',()=>{expect(versions('{"versions":["hey, i\'m in","in","i\'m in, see you at 7"]}')).toEqual(["hey, i'm in",'in',"i'm in, see you at 7"]);const fenced='Sure:\n```json\n{ "versions" : [\n  "line one\\nline \\"two\\"",\n  "caf\\u00e9 at 9" ,"a\\\\b"\n] }\n```';expect(versions(fenced)).toEqual(['line one\nline "two"','café at 9','a\\b']);expect(versions('["one", "two"]')).toEqual([]);});
test('keepsQuotedStructuredDraftText',async()=>{const json='{"versions":["\\\"OK\\\""," keep this ","third"]}';expect(versions(json)).toEqual(['"OK"',' keep this ','third']);const {got,landed}=await run(new Fake(json));expect(got.map(x=>x[1])).toEqual(['"OK"',' keep this ','third']);expect(landed).toContain('LIGHT="OK"');});
test('readsVersionsAsTheyLand',()=>{const full='{"versions":["first one","second\\none","third"]}';const seen=[...full].map((_,i)=>versions(full.slice(0,i+1)).length);expect(seen).toEqual([...seen].sort((a,b)=>a-b));expect([...new Set(seen)]).toEqual([0,1,2,3]);expect(versions('{"versions":["first one","sec')).toEqual(['first one']);expect(versions('{"versions":["first one","a\\u00')).toEqual(['first one']);});
test('notJsonGivesNothing',()=>{expect(versions('ya im in, might be 10 min late')).toEqual([]);expect(versions('{"drafts":["a"]}')).toEqual([]);expect(versions('{"versions":["", "  "]}')).toEqual(['','  ']);});
test('rejectsInvalidEscapesWithoutChangingDrafts',()=>{expect(versions('{"versions":["a\\q","safe"]}')).toEqual([]);expect(versions('{"versions":["a\\u00zz","safe"]}')).toEqual([]);expect(versions('{"versions":["safe","a\\q"]}')).toEqual(['safe']);});
test('promptsCarryTheTextScreenAndRules',()=>{const p=rewritePrompt('ya im in','bro are you still up for padel','No em dashes.');expect(p.endsWith('Screen (context only):\nbro are you still up for padel\n\nTheir text:\nya im in\n\nTheir rules and note: No em dashes.')).toBe(true);expect(p).toContain('{"versions"');expect(p).toContain('1. Light touch');expect(p).toContain('1. Light touch:');expect(p).toContain('\n2. Tighter:');expect(p).toContain('\n3. If it is a new post');expect(rewritePrompt('ya im in','','')).toContain('(none)');const one=versionPrompt('ya im in','',versionsList[1]);expect(one).toContain(versionsList[1].ask);expect(one).not.toContain(versionsList[0].ask);expect(one).not.toContain('JSON');});
class Fake implements RewriteEngine{calls:string[]=[];constructor(private json:string|null,private partials:string[]=[]){ }async ask(prompt:string,_max:number,partial?:(text:string)=>void){if(prompt.includes('{"versions"')){this.calls.push('all');this.partials.forEach(x=>partial?.(x));if(this.json===null)throw new Error('Your phone is busy. Try again in a moment.');return this.json;}const v=versionsList.find(x=>prompt.includes(x.ask))!;this.calls.push(v.name);return v.name==='TIGHTER'&&this.json===''?'':`Here's the new version:\n"${v.label} of it"`;}}
async function run(engine:Fake){const landed:string[]=[];const got=await rewrite(engine,'ya im in','','',(v,t)=>landed.push(`${v.name}=${t}`));return {got,landed};}
test('oneCallWhenTheAnswerIsJson',async()=>{const json='{"versions":["a","b","c"]}';const engine=new Fake(json,['{"versions":["a",','{"versions":["a","b","c','{"versions":["a","b","c"]}']);const {got,landed}=await run(engine);expect(engine.calls).toEqual(['all']);expect(got).toEqual([[versionsList[0],'a'],[versionsList[1],'b'],[versionsList[2],'c']]);expect(landed).toEqual(['LIGHT=a','TIGHTER=b','FIRST=c']);});
test('fallsBackToOneCallPerVersion',async()=>{const engine=new Fake('Sure! Here are three versions: 1. ya im in');const {got,landed}=await run(engine);expect(engine.calls).toEqual(['all','LIGHT','TIGHTER','FIRST']);expect(got.map(x=>x[1])).toEqual(['Cleaned up of it','Shorter of it','Main point first of it']);expect(landed).toHaveLength(3);});
test('fillsOnlyTheVersionsACutShortAnswerMissed',async()=>{const engine=new Fake('{"versions":["a","b","c is cut sh');const {got}=await run(engine);expect(engine.calls).toEqual(['all','FIRST']);expect(got.map(x=>x[1])).toEqual(['a','b','Main point first of it']);});
test('fillsEmptySlotsWithoutChangingVersionLabels',async()=>{const engine=new Fake('{"versions":["","shorter","main point first"]}');const {got,landed}=await run(engine);expect(engine.calls).toEqual(['all','LIGHT']);expect(got.map(([v,t])=>[v.name,t])).toEqual([['LIGHT','Cleaned up of it'],['TIGHTER','shorter'],['FIRST','main point first']]);expect(landed).toContain('TIGHTER=shorter');});
test('skipsAnEmptyVersionAndKeepsTooManyToThree',async()=>{expect((await run(new Fake(''))).got.map(x=>x[0].name)).toEqual(['LIGHT','FIRST']);expect((await run(new Fake('{"versions":["a","b","c","d"]}'))).got.map(x=>x[1])).toEqual(['a','b','c']);});
test('continuesMissingVersionsAfterOneFallbackFails',async()=>{const calls:string[]=[];const engine:RewriteEngine={async ask(prompt){if(prompt.includes('{"versions"'))return '{"versions":["light"]}';const version=versionsList.find(v=>prompt.includes(v.ask))!;calls.push(version.name);if(version.name==='TIGHTER')throw new Error('Your phone is busy. Try again in a moment.');return 'main point first';}};const got=await rewrite(engine,'ya im in','','',()=>{});expect(calls).toEqual(['TIGHTER','FIRST']);expect(got.map(([v,t])=>[v.name,t])).toEqual([['LIGHT','light'],['FIRST','main point first']]);});
test('triesLaterFallbacksAfterTheFirstFails',async()=>{const calls:string[]=[];const error=new Error('Your phone is busy. Try again in a moment.');const engine:RewriteEngine={async ask(prompt){if(prompt.includes('{"versions"'))return 'not json';const version=versionsList.find(v=>prompt.includes(v.ask))!;calls.push(version.name);if(version.name==='LIGHT')throw error;return version.name;}};const got=await rewrite(engine,'ya im in','','',()=>{});expect(calls).toEqual(['LIGHT','TIGHTER','FIRST']);expect(got.map(([v,t])=>[v.name,t])).toEqual([['TIGHTER','TIGHTER'],['FIRST','FIRST']]);await expect(rewrite({ask:async prompt=>{if(prompt.includes('{"versions"'))return 'not json';throw error;}},'ya im in','','',()=>{})).rejects.toBe(error);});
test('anErrorBeforeAnyVersionReachesTheUser',async()=>{await expect(run(new Fake(null))).rejects.toBeInstanceOf(Error);});
