import 'expo-router/entry';
import React from 'react';
import { AppRegistry } from 'react-native';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import Panel from './src/panel/Panel';
import Rewrite from './src/rewrite/Rewrite';
import Voice from './app/voice';
import Native from './modules/ownvoice-native';
const RewriteEntry = () => Native.rewriteInput()?.markdown ? React.createElement(Voice, { shared: true }) : React.createElement(Rewrite);
const wrap = Component => () => React.createElement(SafeAreaProvider, null, React.createElement(Component));
AppRegistry.registerComponent('panel', () => wrap(Panel));
AppRegistry.registerComponent('rewrite', () => wrap(RewriteEntry));
