export const CHATGPT_TERMS = 'Uses your ChatGPT plan.';
export const technicalWords = /(?:gemini|gemma|\bnano\b|aicore|ml ?kit|\bllm\b|\bmodel\b|\/100|\/10\b|judge|slop|characters|\bprompt|\btokens?\b|on-device|gpt-\d|codex|openai api|responses|%|\bpercent\b|\(\d{3}\))/i;
export const plainReason = (reason: string) => !technicalWords.test(reason) && !/\d/.test(reason) && reason.trim().split(/\s+/).length <= 12;
export const words = {
  writeFirst:'Write a line or two first, and Ownvoice will help you polish it.',
  quickChecks:'These are quick checks to help you choose.',
  gettingReady:'Getting Ownvoice ready… this happens once.',
  writing:'Writing…',
  nothingYet:'Nothing to reply to yet',
  replyTitle:'Suggested replies',
  polishTitle:'Polish your message',
  toneSounds:'Sounds',
  postTitle:'Polish your post',
  ownTitle:'Start your post',
  ownNote:'Nothing on screen to work from, so these ask what the post is about. Edit one, then post it yourself.',
  noOpeners:"Couldn't write any openers this time. Try again.",
  readyReply:'Pick one to put in your message box. You send it yourself.',
  readyPolish:'Pick one to use instead of what you wrote. You send it yourself.',
  noField:'Tap into the message box first to use Insert, or copy one.',
  noCapture:'Nothing to read on this screen. Close this and tap the bubble again.',
  noReplies:'Couldn\'t come up with replies this time. Try again.',
  noVersions:'Couldn\'t polish that this time. Try again.',
  looksGood:'No different version found',
  looksGoodNote:'Read it over before you send it.',
  serviceOff:'Ownvoice is off. Use Copy instead.',
  fallback:'ChatGPT didn\'t answer. This phone wrote these instead.',
  phoneWrote:'This phone wrote these.',
  switchUnavailable:'ChatGPT could not be reached this time. This phone wrote these.',
  chatgptFailed:'ChatGPT didn\'t answer this time.',
  tryAgain:'Try again',
  writeNew:'Write new ones',
  insert:'Insert',
  useThis:'Use this',
  copy:'Copy',
  copied:'Copied',
  why:'Why?',
  whyReply:'Why this reply',
  whyVersion:'Why this version',
  howItReads:'How it reads',
  checking:'Checking…',
  noChecks:'The deeper checks have not run.',
  unsupported:"Sorry, Ownvoice doesn't work on this phone yet.",
  busy:'Your phone is busy. Try again in a moment.',
  batteryQuota:'Ownvoice needs a short break. Try again in a little while.',
  backgroundBlocked:'Open Ownvoice again and try once more.',
  noSpace:'Your phone needs a bit more free space to get Ownvoice ready.',
  requestTooLarge:'That chat is too long. Scroll to the latest messages and tap again.',
  systemUpdate:'Your phone needs an update first. Open Settings › System updates, then try again.',
  failed:'Something went wrong. Try again.',
  switchNote:'Ownvoice checks now and then whether ChatGPT is allowed to write. That check carries no name and no message.',
  welcomeTitle:'Write replies that sound like you.',
  welcomeNote:'Tap the bubble in any chat. Ownvoice writes a reply in your words, and you press Send.',
  welcomeReply:'Yes! I’ll bring the stove. See you Saturday.',
  permissionNext:'On the next screen',
  continueLabel:'Continue',
  permissionTitle:'Let Ownvoice see your chats, only when you tap',
  permissionSubtitle:'Android calls this “accessibility”. It’s the only way a helper can read a chat and fill in a message box for you.',
  promiseTap:'Reads only when you tap the bubble',
  promiseTapNote:'Never in the background',
  promiseSend:'You always press Send',
  promiseSendNote:'Ownvoice never sends for you',
  switchRowApp:'Ownvoice',
  switchRowAction:'Use Ownvoice',
  on:'On',
  off:'Off',
  stepApp:'Tap “Ownvoice”',
  stepSwitch:'Switch on “Use Ownvoice”',
  stepAllow:'Tap “Allow”',
  fullControl:'Android asks to allow “full control”. It asks that of every helper like this one.',
  turnOn:'Turn on',
  notNow:'Not now',
  switchGreyed:'Switch greyed out?',
  greyedHelp:'In App info, tap ⋮ at the top, then “Allow restricted settings”. Then come back and tap Turn on.',
  tryTitle:'Try it',
  tryInsert:'Tap the round bubble on the right, then Insert.',
  tryTurnOnFirst:'Turn Ownvoice on first, then come back here to try it.',
  tryDoneTitle:'You did it',
  tryDone:'That’s it. In your apps, read it over and press Send yourself.',
  practiceFriend:'Sam',
  practiceMessage1:'Are we still on for Saturday?',
  practiceMessage2:'I can bring the tent if you bring the stove.',
  practiceField:'Practice message',
  practiceNote:'It’s only practice: nothing here goes to anyone.',
  gptButton:'Continue with ChatGPT',
  gptCancel:'Cancel',
  gptSignOut:'Sign out of ChatGPT',
  gptAppsUnavailable:'Couldn’t load your choices. Try again.',
  gptAppsSaveFailed:'Couldn’t save that. Try again.',
  gptSignedInNow:'ChatGPT is connected.',
  readsTitle:'What Ownvoice read',
  gptSignOutFailed:'Couldn’t sign out. Try again.',
  gptPageFailed:'Couldn’t open the ChatGPT page. Try the button again.',
  skip:'Skip',
  appsTitle:'Where should I help?',
  appsNote:'The bubble shows only in these apps. You can change this any time.',
  appsUnavailable:'Couldn’t find your apps. Try again.',
  done:'Done',

  // Home (MainActivity).
  homeTitle:'Ownvoice',
  statusOff:'Ownvoice is off',
  statusOffNote:'Turn it on to use the bubble',
  statusReady:'Ready to help',
  statusReadyNote:'Tap the bubble in your chats',
  statusGettingReady:'Getting ready…',
  statusNotReady:'Not ready yet',
  statusNotReadyNote:'Tap Try again to get Ownvoice ready.',
  statusPaused:'Paused',
  statusPausedNote:'The bubble is hidden everywhere',
  powerRow:'Ownvoice on or off',
  turnBackOn:'Turn back on',
  rowApps:'Where the bubble shows',
  rowVoice:'Your voice',
  rowReads:'What Ownvoice read',
  noApps:'No apps yet',
  noPhrases:'Add phrases you never say',
  phraseOne:'phrase you never say',
  phraseMany:'phrases you never say',
  timesWeek:'times this week',
  nothingWeek:'Nothing this week',
  onceWeek:'Once this week',
  back:'Back',
  rowPause:'Pause for now',
  rowPauseNote:'Hides the bubble everywhere',
  rowRewrite:'Rewrite any text',
  tip:'Tip',
  rowRewriteNote:'Select text in any app, then choose Ownvoice',

  // Where the bubble shows (AppsActivity).
  appsScreenNote:"In apps that are off, the bubble doesn't show and nothing is read.",
  findAnApp:'Find an app',
  clearSearch:'Clear',
  appsShown:'Bubble shows in',
  appsOther:'Other apps',
  appsNoneShown:'None yet. Switch on an app below.',
  appsNoMatch:'No app with that name.',

  // Your voice (VoiceActivity).
  voiceNote:'Phrases you never say and how you like to write. Ownvoice follows these when it writes, and points out when a draft breaks them. They stay on this phone.',
  importFile:'Import from a file',
  cantOpen:"Couldn't open that file.",
  foundNothing:"Couldn't find any phrases in that file.",
  foundHead:'Found in the file:',
  foundRest:'Nothing else in the file is kept. Add these to Your voice?',
  foundNever:'Never say',
  foundRuleDashes:'Rule: No long dashes (—)',
  foundRuleEndings:'Rule: End posts on a statement, not a question',
  added:'Added. Edit or delete anything below.',
  addThese:'Add these',
  cancel:'Cancel',
  ruleDashes:'No long dashes (—)',
  ruleDashesNote:"Ownvoice won't use them",
  ruleEndings:'End posts on a statement',
  ruleEndingsNote:'Questions are still fine in replies',
  howIWrite:'How I write',
  howIWriteHint:'For example: short sentences, lowercase, blunt',
  neverSay:'Never say',
  neverSayHint:'Add a phrase',
  neverSayHelp:"Ownvoice won't write these, and marks them if a draft uses one.",
  neverSayNone:'Nothing here yet. Tap one to start, or add your own.',
  howIWriteIdeas:'Tap any that sound like you.',
  addPhrase:'Add',
  removePhrase:'Remove',
  rulesTitle:'Rules',
  wipeElsewhere:'Wipe everything, under What Ownvoice read, deletes these too.',

  // What Ownvoice read (ReadsActivity).
  readsNote:'Each time you tap the bubble, Ownvoice notes the app, the time, what it helped with and whether ChatGPT saw the screen. Never any of your text. This list stays on this phone and each entry is deleted after 30 days.',
  wipe:'Wipe everything',
  wipeVoiceNote:'Wipe everything also deletes Your voice.',
  nothingRead:'Nothing read in the last 30 days.',
  today:'Today',
  yesterday:'Yesterday',
  wipeAsk:'This deletes the list above and Your voice from this phone. They can’t be brought back.',
  wipeYes:'Wipe',

  // How Ownvoice writes (the choice: setup, sign-in, settings, Home, panel).
  chooseTitle:'How should Ownvoice write?',
  chooseNote:'Pick one. You can change it any time.',
  chooseNoteCant:'This phone can\'t write drafts on its own, so Ownvoice needs your ChatGPT.',
  srcPhone:'On this phone',
  srcPhoneSub:'Private and free',
  srcPhoneCant:'This phone can\'t write on its own. Only some newer phones can.',
  whyNot:'Why not?',
  phoneCantWhy:'Writing right on the phone needs a newer phone with its own built-in writer. This phone doesn’t have one, so Ownvoice writes with your ChatGPT instead. You still pick each draft and press Send yourself.',
  srcGpt:'With your ChatGPT',
  srcGptSub:'The plan you already pay for',
  tradePhone1:'Nothing you read or write leaves this phone',
  tradePhone2:'Free, and works without internet',
  tradePhone3:'Simpler drafts, and a bit slower on some phones',
  tradeGpt1:'Sharper drafts, usually quicker',
  tradeGpt2:'Needs internet, and uses your ChatGPT plan',
  tradeGpt3:'When you tap the bubble, what\'s on screen goes to ChatGPT',
  signInTitle:'Sign in to ChatGPT',
  signInNote:'On the ChatGPT page, type this code. Then come back here.',
  yourCode:'Your code',
  waiting:'Waiting for you to sign in…',
  copyAndOpen:'Copy code and open ChatGPT',
  connectedNote:'Ownvoice will write your drafts with your ChatGPT.',
  usePhoneInstead:'Use this phone instead',
  rowSource:'How Ownvoice writes',
  rowSourcePhone:'On this phone',
  rowSourceGpt:'With your ChatGPT',
  rowSourceNone:'Not chosen yet',
  sourceNote:'Choose who writes your drafts. You can switch any time.',
  // What each reply is for, in the order the writers fill them (chat slots in platforms.ts).
  replyYes:'Say yes',
  replyNo:'Say no, kindly',
  replyAsk:'Ask first',
  // The same three jobs in each app's own words (the slots in platforms.ts).
  tagAgree:'Agree',
  tagPushBack:'Push back, kindly',
  tagQuestion:'Ask a question',
  tagOtherView:'Another view',
  tagFollowUp:'Ask a follow-up',
  tagAnswer:'Answer',
  tagDisagree:'Disagree',
  tagDetail:'Ask for a detail',
  tagConfirm:'Confirm',
  tagBlocker:'Flag a blocker',
  tagUnclear:'Ask what’s unclear',
  tagAccept:'Accept',
  writingSection:'What happens to your writing',
  headGpt:'Your chat goes to ChatGPT only when you tap',
  headPhone:'Nothing leaves this phone',
  headSwitch:'A quick check, with no name or message',
  headReads:'A list of taps, never your text',
  privacyPhone:'Nothing you read or write leaves this phone. Ownvoice writes your drafts right here.',
  privacyGpt:'When you tap the bubble, the chat on screen, what you typed and your writing rules go to ChatGPT. Ownvoice keeps no copy.',
  sentOnlyOnTap:'Nothing is sent at any other time.',
  phoneBackup:'If ChatGPT can\'t answer, this phone writes instead.',
  phoneOnlyApps:'Apps that stay on this phone',
  phoneOnlyNote:'These apps are always written on this phone.',
  switchTitle:'Write with ChatGPT?',
  switchBody:'From now on, when you tap the bubble, the chat on screen and what you typed go to ChatGPT to write your drafts.',
  switchYes:'Switch to ChatGPT',
  switchNo:'Keep it on this phone',
  needWriter:'Choose how Ownvoice writes',
  needWriterNote:'This phone can\'t write drafts on its own. Sign in with your ChatGPT to use Ownvoice here.',
  needWriterPanel:'Choose how Ownvoice writes first.',
  phoneOnlyCant:'This app is set to stay on this phone, and this phone can\'t write. Open Ownvoice to change that.',
  openOwnvoice:'Open Ownvoice',
  homePhone:'Writes on this phone.',
  homeGpt:'Writes with your ChatGPT.',
  offlinePhone:'You\'re not connected to the internet. This phone wrote these.',
  offlineNoPhone:'You\'re not connected to the internet. Connect, then try again.',
  gptFailedNoPhone:'ChatGPT didn\'t answer this time.',
  gptOffNoPhone:'ChatGPT is turned off for now. Try again later.',
  restingPhone:'This phone writes until then.',
  promiseStays:'Stays on this phone',
  promiseStaysNote:'Nothing you read or write leaves your phone',
  promiseGpt:'Goes only to your ChatGPT',
  promiseGptNote:'Only when you tap the bubble',

  // The one-time download of the phone's writer: asked for only after the person picks this phone.
  readyTitle:'Get this phone ready to write',
  readyNote:'It needs about 2 to 3 GB, once, on Wi-Fi. Nothing you write leaves the phone.',
  getReady:'Get it ready',
  readyStopped:'Getting ready stopped. Connect to Wi-Fi, then tap Try again.',
  useMobileData:'Use mobile data instead',
  readyPanel:'Open Ownvoice to get this phone ready to write.',
  phoneReady:'Ready. It writes right here.',
  removeRow:'Free up space',
  removeRowNote:'Removes what this phone downloaded to write. You can get it again later.',
  removeAsk:'Ownvoice won’t write on this phone until you get it ready again, which takes about 2 to 3 GB on Wi-Fi.',
  removeYes:'Remove',
  removeNo:'Keep it',
  removeFailed:"That didn't work. Please try again.",

  // Prefill hand-off (parity package 6): the app's own compose opens with the text; the person presses Post or Send.
  openInX:'Open in X with this text',
  openInWhatsapp:'Open in WhatsApp with this text',
  shareText:'Share this text',

  // Thread writer and hooks (parity package 5): from text they typed in a feed app.
  threadTitle:'Split into a thread',
  threadReady:'Post these in order. You send each one yourself.',
  hooksTitle:'Opening lines',

  // Lab builds only (EXPO_PUBLIC_PHONE_AGENT=1): the writing-task screen.
  agentRow:'Try a writing task',
  agentAsk:'What should I write?',
  agentGo:'Write it',
  agentChecking:'Checking it against your rules…',
  agentShareTitle:'Share this note?',
  agentShare:'Share',
  agentNotNow:'Not now',
  agentCant:"I can't send email or change your calendar from here. You can share the note and paste it where you need it.",
  agentStopped:'I stopped here. This is the latest version.',

} as const;
