import * as Slop from './slop';
import * as Voice from './voice';
import {plainReason, words} from './words';
export type Check={name:string;ok:boolean;reason:string};
export type Verdict={good:boolean;lead:string;rest:string};
export type Mode='COMPOSE'|'REPLY'|'EMPTY';
export type Scores={hits:Slop.Hit[];generic:number|null;specific:number|null;quality:Check[];reach:Check[];message:boolean;slop:number};
type Kind={key:string;pass:string;concern:string};
const v:Kind={key:'VOICE',pass:'Sounds like you',concern:"Doesn't sound like you"};
const quality:Kind[]=[{key:'SPECIFIC',pass:'Says something real',concern:'Could be more specific'},{key:'CLEAR',pass:'One clear point',concern:"The point isn't clear"},v,{key:'FITS',pass:'Fits the conversation',concern:"Doesn't quite fit the conversation"},{key:'CLAIMS',pass:"Doesn't make anything up",concern:'Might make something up'}];
const reach:Kind[]=[{key:'CONVERSATION',pass:'Invites replies',concern:"Doesn't invite replies"},{key:'NOT_INTERESTED',pass:"Won't put people off",concern:'Might put people off'},{key:'HOOK',pass:'Strong first line',concern:'Weak first line'}];
const response=(who?:string|null):Kind[]=>[{key:'ANSWERS',pass:`Answers ${who||'the question'}`,concern:`Doesn't answer ${who||'everything asked'}`},{key:'NEXT_STEP',pass:'Clear what happens next',concern:'Not clear what happens next'}];
export const GENERAL='A bit general';
export const quickChecks=(who?:string|null)=>words.quickChecks+(who?` You know ${who} best.`:'');
export function who(text:string):string|null{const names=[...text.matchAll(/^\s*(\p{Lu}[\p{L}'’-]{0,20}):\s+\S/gmu)].map(m=>m[1]).filter(n=>n!=='You'&&n!=='Me');const unique=[...new Set(names.filter(n=>names.filter(x=>x===n).length>=2))];return unique.length===1?unique[0]:null;}
export const kindPrompt=(c:string)=>`Below is the text on someone's phone screen. Which kind of screen is it?\nMESSAGE: a private chat or direct message between a few people, or an email.\nPOST: a public post, feed or comment thread that many people read; it often shows @handles, likes, reposts, comment counts or times like 2h.\n\nScreen:\n${c.slice(-1500)}\n\nAnswer with one word: MESSAGE or POST.`;
export const isMessage=(a:string):boolean|null=>/^\s*MESSAGE\.?\s*$/i.test(a)?true:/^\s*POST\.?\s*$/i.test(a)?false:null;
export function draftPrompt(c:string,d:string,message:boolean,guide=''){return `You check a reply draft before someone sends it. Be strict, and brief. Casual tone, typos and bluntness are fine.\n\nScreen (the conversation, may include app labels):\n${c.slice(-2000)}\n\nDraft reply:\n${d}${guide?`\n\nThe person's own writing rules: ${guide}`:''}\n\nAnswer in exactly these lines and nothing else. Explain each check in everyday words for someone with no technical knowledge. Each check line is pass or concern, a dash, and at most 8 words.\nGENERIC: 0-10 (10 = could be sent to anyone about anything)\nSPECIFICITY: 0-10 (10 = concrete details from this conversation)\nSPECIFIC: pass or concern - does it say something concrete?\nCLEAR: pass or concern - does it make one clear point?\nVOICE: pass or concern - does it match how the person writes on screen${guide?' and follow their rules?':'?'}\nFITS: pass or concern - does its length and tone fit this thread?\nCLAIMS: pass or concern - concern if it states facts about the writer, numbers, plans or products the screen doesn't support\n${message?'ANSWERS: pass or concern - does it answer every question asked?\nNEXT_STEP: pass or concern - is the next step or time clear?':'CONVERSATION: pass or concern - would people want to reply to it?\nNOT_INTERESTED: pass or concern - concern if readers may find it off-putting, salesy or irrelevant\nHOOK: pass or concern - does its first line make people read on?\n'}`;}
export function parse(answer:string):Record<string,string>{return Object.fromEntries(answer.split(/\r?\n/).flatMap(line=>{const m=line.match(/^[\s*#>•-]*([A-Za-z_ ]+?)[*\s]*:[*\s]*(.+)$/);return m?[[m[1].trim().toUpperCase().replace(/ /g,'_'),m[2].trim()]]:[]}));}
function checks(lines:Record<string,string>, kinds:Kind[]):Check[]{return kinds.flatMap(k=>{const value=lines[k.key];if(!value)return[];const m=value.match(/^[\s–—-]*(pass|concern)\b[\s:,.;–—-]*/i);if(!m)return[];const ok=m[1].toLowerCase()==='pass';const reason=value.slice(m[0].length).trim();const safe=reason&&plainReason(reason)?reason:(k.key==='MEANING'?'It may change what you meant.':k.concern+'.');return [{name:ok?k.pass:k.concern,ok,reason:safe[0].toUpperCase()+safe.slice(1)}];});}
export const number=(v?:string)=>{const n=v?.match(/\d+/)?.[0];return n===undefined?null:Math.min(10,Number(n));};
export function validDraftAnswer(answer:string,message:boolean):boolean{const lines=parse(answer);return number(lines.GENERIC)!==null&&number(lines.SPECIFICITY)!==null&&checks(lines,quality).length===quality.length&&checks(lines,message?response():reach).length===(message?response():reach).length;}
export function scoreDraft(draft:string,answer:string|null,message:boolean,voice:Slop.Rules=Slop.NO_RULES,post=false,person?:string|null):Scores{const lines=answer?parse(answer):{};const hits=Slop.hits(draft,voice,post&&!message);const broken=Voice.broken(hits,draft,voice);const q=checks(lines,quality).filter(x=>!(broken.length&&[v.pass,v.concern].includes(x.name)));if(broken.length)q.splice(Math.min(quality.indexOf(v),q.length),0,{name:v.concern,ok:false,reason:'Breaks your rules: '+broken.join('; ')+'.'});const r=checks(lines,message?response(person):reach);if(!message){if(/https?:\/\/|www\./.test(draft))r.push({name:'Links can mean fewer views',ok:false,reason:'Feeds may show posts with links to fewer people.'});r.push(draft.length>280?{name:'Long for a post',ok:false,reason:'Shorter posts get read more.'}:{name:'Right length for a post',ok:true,reason:''});}const generic=number(lines.GENERIC),specific=number(lines.SPECIFICITY);return {hits,generic,specific,quality:q,reach:r,message,slop:Slop.score(hits.length,generic,specific)};}
export function verdict(s:Scores):Verdict{const concern=[...s.quality,...(s.message? s.reach:[])].find(x=>!x.ok);const lead=Slop.words(s.slop);if(!Slop.natural(s.slop))return s.hits.length?{good:false,lead,rest:`: ${s.hits.length===1?'a phrase':`${s.hits.length} phrases`} you could say more simply`}:{good:false,lead:concern?.name||GENERAL,rest:''};if(concern)return {good:false,lead:concern.name,rest:''};const ans=s.reach.find(x=>x.name.startsWith('Answers'));return {good:true,lead,rest:ans?' and '+ans.name[0].toLowerCase()+ans.name.slice(1):''};}
export const mode=(typed:string,written:string):Mode=>typed.trim()?'COMPOSE':replying(written)?'REPLY':'EMPTY';
export const replying=(written:string)=>written.split(/\r?\n/).some(l=>l.trim().split(/\s+/).length>=4);
export const WRITE_FIRST=words.writeFirst;
export enum Rewrite{TIGHTEN='Shorter',PLAINER='Simpler',GRAMMAR='Fix spelling'}
export enum Boost{TIGHTER='Shorter',PLAINER='More like you',DETAIL='Start with a detail'}
const REWRITE_RULES=`Rules for every version:\n- Keep every fact, number, name, plan and promise; add none. Never add experience, results, promises, "we" or anything they didn't write. Don't answer anything they didn't answer.\n- Keep their stance and their voice: same language, same casing, no more formal than they wrote. A chat stays a chat.\n- Cut template phrasing: hype words ("game-changer", "excited to announce"), "in today's world", "not just X, it's Y" and "more than just", "I'd love to hear your thoughts", "let me know your thoughts", flattery openers ("Great post", "Great question"), hashtag lists. Don't add long dashes (—).\n- Keep their layout: the same line breaks and paragraphs; a list stays a list with the same markers (1. 2. or -); keep their emoji.\n- If a sentence is only template, drop it.`;
const dashRule=(dashes:'keep'|'remove')=>`- their dashes: ${dashes}`;
export function rewritePrompt(text:string,screen:string,guide='',dashes:'keep'|'remove'='remove'){return `You improve a text someone wrote on their phone, before they send it. The screen is context only.\nReturn 3 versions of THEIR text, in this order:\n${versionsList.map((v,i)=>`${i+1}. ${v.ask}`).join('\n')}\n${REWRITE_RULES}\n${dashRule(dashes)}\n- Each version must read naturally and be clearly different from the other two, unless the text is already fine: then version 1 may equal their text.\n- Follow their rules and note. Output only JSON: {"versions":["...","...","..."]}\n\nScreen (context only):\n${screen.slice(-1500)||'(none)'}\n\nTheir text:\n${text}${guide?`\n\nTheir rules and note: ${guide}`:''}`;}
export function rewriteCheckPrompt(original:string,rewrite:string){return `Compare a rewrite with its original. Be strict, and brief.\n\nOriginal:\n${original}\n\nRewrite:\n${rewrite}\n\nAnswer in exactly these lines and nothing else.\nGENERIC: 0-10 (10 = the rewrite could be sent to anyone about anything)\nSPECIFICITY: 0-10 (10 = the rewrite has concrete details)\nMEANING: pass or concern - concern if the rewrite adds, drops or changes a claim, fact, number or promise; explain in everyday words for someone with no technical knowledge, at most 10 words\n`;}
export function meaning(original:string,rewrite:string,answer:string|null):Check|null{const a=Slop.addedNumbers(original,rewrite),b=Slop.addedNumbers(rewrite,original);const quote=(xs:string[])=>xs.map(x=>`“${x}”`).join(' and ');const changes=[a.length?'adds '+quote(a):'',b.length?'leaves out '+quote(b):''].filter(Boolean);if(changes.length)return {name:'Meaning',ok:false,reason:'It '+changes.join(' and ')};return checks(answer?parse(answer):{},[{key:'MEANING',pass:'Same meaning',concern:'Check this'}])[0]||null;}
export function clean(text:string){const lines=text.trim().split(/\r?\n/);const body=lines.length>1&&/^here/i.test(lines[0].trim())&&lines[0].trim().endsWith(':')?lines.slice(1):lines;return body.join('\n').trim().replace(/^"([\s\S]*)"$/,'$1').trim();}
export type Version={name:'LIGHT'|'TIGHTER'|'FIRST';label:string;ask:string};
export const versionsList:Version[]=[{name:'LIGHT',label:'Cleaned up',ask:'Light touch: fix spelling, grammar and punctuation, and cut any template phrase listed below. Change nothing else; keep their casing and slang.'},{name:'TIGHTER',label:'Shorter',ask:'Tighter: the same points in fewer words, in their voice.'},{name:'FIRST',label:'Main point first',ask:'If it is a new post: open with the most concrete detail already in it. If it replies to someone: put the answer first, then the rest, reading naturally.'}];
export function versionPrompt(text:string,screen:string,version:Version,guide='',dashes:'keep'|'remove'='remove'){return `You improve a text someone wrote on their phone, before they send it. The screen is context only.\nReturn one version of THEIR text. ${version.ask}\n${REWRITE_RULES}\n${dashRule(dashes)}\n- Follow their rules and note. Output only the new version of their text.\n\nScreen (context only):\n${screen.slice(-1500)||'(none)'}\n\nTheir text:\n${text}${guide?`\n\nTheir rules and note: ${guide}`:''}`;}
export function versions(answer:string):string[]{const list=answer.match(/"versions"\s*:\s*\[/);if(!list)return[];let i=list.index!+list[0].length;const out:string[]=[];while(true){while(i<answer.length&&(/\s/.test(answer[i])||answer[i]===','))i++;if(i>=answer.length||answer[i]!=='"')return out;let value='';i++;while(true){if(i>=answer.length)return out;const c=answer[i++];if(c==='"')break;if(c!=='\\'){value+=c;continue;}if(i>=answer.length)return out;const e=answer[i++];if(e==='u'){if(i+4>answer.length)return out;const hex=answer.slice(i,i+4);if(!/^[\da-fA-F]{4}$/.test(hex))return out;value+=String.fromCharCode(Number.parseInt(hex,16));i+=4;}else if(e==='n')value+='\n';else if(e==='t')value+='\t';else if(e==='r')value+='\r';else if(e==='b')value+='\b';else if(e==='f')value+='\f';else if(e==='"'||e==='\\'||e==='/')value+=e;else return out;}out.push(value);}}
export type RewriteEngine={ask(prompt:string,maxTokens:number,partial?:(text:string)=>void):Promise<string>}
export async function rewrite(engine:RewriteEngine,text:string,screen:string,guide:string,landed:(version:Version,text:string)=>void,dashes:'keep'|'remove'='remove'):Promise<[Version,string][]>{const got:([Version,string]|undefined)[]=[];const take=(found:string[])=>{found.slice(0,versionsList.length).forEach((value,i)=>{if(value.trim()&&!got[i]){got[i]=[versionsList[i],value];landed(versionsList[i],value);}});};try{take(versions(await engine.ask(rewritePrompt(text,screen,guide,dashes),256,partial=>take(versions(partial)))));}catch(error){if(!got.some(Boolean))throw error;}let failure:unknown;for(let i=0;i<versionsList.length;i++){if(got[i])continue;const version=versionsList[i];let value='';try{value=clean(await engine.ask(versionPrompt(text,screen,version,guide,dashes),256));}catch(error){failure=error;continue;}if(value){got[i]=[version,value];landed(version,value);}}if(!got.some(Boolean)&&failure!==undefined)throw failure;return got.filter((entry):entry is [Version,string]=>!!entry);}
