export const CHATGPT_TERMS = 'Uses your ChatGPT plan.';
export const technicalWords = /(?:gemini|gemma|\bnano\b|aicore|ml ?kit|\bllm\b|\bmodel\b|\/100|\/10\b|judge|slop|characters|\bprompt|\btokens?\b|on-device|gpt-\d|codex|openai api|responses|%|\bpercent\b|\(\d{3}\))/i;
export const plainReason = (reason: string) => !technicalWords.test(reason) && !/\d/.test(reason) && reason.trim().split(/\s+/).length <= 12;
export const words = {
  writeFirst:'Write a line or two first, and Ownvoice will help you polish it.',
  quickChecks:'These are quick checks to help you choose.',
  gettingReady:'Getting Ownvoice ready… this happens once.',
  writing:'Writing…',
  nothingYet:'Nothing to reply to yet',
  replyTitle:'Suggested replies',
  polishTitle:'Polish your message',
  postTitle:'Polish your post',
  readyReply:'Pick one to put in your message box. You send it yourself.',
  readyPolish:'Pick one to use instead of what you wrote. You send it yourself.',
  noField:'Tap into the message box first to use Insert, or copy one.',
  noCapture:'Nothing to read on this screen. Close this and tap the bubble again.',
  noReplies:'Couldn\'t come up with replies this time. Try again.',
  noVersions:'Couldn\'t polish that this time. Try again.',
  serviceOff:'Ownvoice is off. Use Copy instead.',
  fallback:'ChatGPT didn\'t answer. This phone wrote these instead.',
  chatgptFailed:'ChatGPT didn\'t answer this time.',
  tryAgain:'Try again',
  writeNew:'Write new ones',
  insert:'Insert',
  useThis:'Use this',
  copy:'Copy',
  why:'Why?',
  whyReply:'Why this reply',
  whyVersion:'Why this version',
  howItReads:'How it reads',
  checking:'Checking…',
  noChecks:'Couldn\'t run the other checks this time.',
  unsupported:"Sorry, Ownvoice doesn't work on this phone yet.",
  busy:'Your phone is busy. Try again in a moment.',
  batteryQuota:'Ownvoice needs a short break. Try again in a little while.',
  backgroundBlocked:'Open Ownvoice again and try once more.',
  noSpace:'Your phone needs a bit more free space to get Ownvoice ready.',
  requestTooLarge:'That chat is too long. Scroll to the latest messages and tap again.',
  systemUpdate:'Your phone needs an update first. Open Settings › System updates, then try again.',
  failed:'Something went wrong. Try again.',
  home:'Your writing helper. It writes on this phone, or with your ChatGPT plan.',
  privacyNote:'With the phone’s own writer, nothing leaves your phone. If you sign in to ChatGPT, the chat on your screen and what you typed are sent to ChatGPT to write your drafts.',
  switchNote:'Ownvoice checks now and then whether ChatGPT is allowed to write. That check carries no name and no message.',
  permission:'On the next screen, tap Ownvoice, then switch on “Use Ownvoice”:',
  welcomeTitle:'Write replies that sound like you.',
  continueLabel:'Continue',
  permissionTitle:'Let Ownvoice see your chats, only when you tap',
  permissionSubtitle:'Android calls this “accessibility”. It’s the only way a helper can read a chat and fill in a message box for you.',
  promiseTap:'Reads only when you tap the bubble',
  promiseTapNote:'Never in the background',
  promisePhone:'Choose who writes your drafts',
  promisePhoneNote:'Nothing leaves your phone unless you sign in to ChatGPT',
  promiseSend:'You always press Send',
  promiseSendNote:'Ownvoice never sends for you',
  switchRowApp:'Ownvoice',
  switchRowAction:'Use Ownvoice',
  on:'On',
  off:'Off',
  fullControl:'Android then asks to allow “full control”. It asks that of every helper like this one. Tap Allow.',
  turnOn:'Turn on',
  notNow:'Not now',
  switchGreyed:'Switch greyed out?',
  greyedHelp:'In App info, tap ⋮ at the top, then “Allow restricted settings”. Then come back and tap Turn on.',
  tryTitle:'Try it',
  tryInsert:'Tap the round bubble on the right, then Insert.',
  tryTurnOnFirst:'Turn Ownvoice on first, then come back here to try it.',
  tryDone:'That’s it. In your apps, read it over and press Send yourself.',
  practiceFriend:'Sam',
  practiceMessage1:'Are we still on for Saturday?',
  practiceMessage2:'I can bring the tent if you bring the stove.',
  practiceField:'Practice message',
  practiceNote:'It’s only practice: nothing here goes to anyone.',
  gptTitle:'Write with ChatGPT',
  gptNote:'ChatGPT writes your drafts with the plan you already pay for. This phone writes them if ChatGPT can’t.',
  gptButton:'Continue with ChatGPT',
  gptOpenPage:'Open the ChatGPT page',
  gptCancel:'Cancel',
  gptSignOut:'Sign out of ChatGPT',
  gptApps:'Apps that can use ChatGPT',
  gptAppsQuestion:'Which apps can use ChatGPT?',
  gptAppsNote:'ChatGPT writes only in the apps you switch on. The rest are written on this phone.',
  gptAppsUnavailable:'Couldn’t load your choices. Try again.',
  gptAppsSaveFailed:'Couldn’t save that. Try again.',
  gptAppsSignIn:'Sign in to ChatGPT again, then try Done.',
  gptSignedInNow:'ChatGPT is connected.',
  readsTitle:'What Ownvoice read',
  gptSignOutFailed:'Couldn’t sign out. Try again.',
  gptPageFailed:'Couldn’t open the ChatGPT page. Try the button again.',
  skip:'Skip',
  appsTitle:'Where should I help?',
  appsNote:'The bubble shows only in these apps. You can change this any time.',
  appsUnavailable:'Couldn’t find your apps. Try again.',
  done:'Done',

  // Home (MainActivity).
  homeTitle:'Ownvoice',
  statusOff:'Ownvoice is off',
  statusOffNote:'Turn it on to use the bubble',
  statusReady:'Ready to help',
  statusReadyNote:'Tap the bubble in your chats',
  statusGettingReady:'Getting ready…',
  statusNotReady:'Not ready yet',
  statusNotReadyNote:'Tap Try again to get Ownvoice ready.',
  statusPaused:'Paused',
  statusPausedNote:'The bubble is hidden everywhere',
  powerRow:'Ownvoice on or off',
  turnBackOn:'Turn back on',
  rowApps:'Where the bubble shows',
  rowVoice:'Your voice',
  rowReads:'What Ownvoice read',
  noApps:'No apps yet',
  noPhrases:'Add phrases you never say',
  phraseOne:'phrase you never say',
  phraseMany:'phrases you never say',
  timesWeek:'times this week',
  nothingWeek:'Nothing this week',
  onceWeek:'Once this week',
  back:'Back',
  rowPause:'Pause for now',
  rowPauseNote:'Hides the bubble everywhere',
  rowRewrite:'Rewrite any text',
  rowRewriteNote:'Select text in any app, then choose Ownvoice',

  // Where the bubble shows (AppsActivity).
  appsScreenNote:"In apps that are off, the bubble doesn't show and nothing is read.",
  findAnApp:'Find an app',

  // Your voice (VoiceActivity).
  voiceNote:'Phrases you never say and how you like to write. Ownvoice follows these when it writes, and points out when a draft breaks them. They stay on this phone.',
  importFile:'Import from a file',
  cantOpen:"Couldn't open that file.",
  foundNothing:"Couldn't find any phrases in that file.",
  foundHead:'Found in the file:',
  foundRest:'Nothing else in the file is kept. Add these to Your voice?',
  foundNever:'Never say',
  foundRuleDashes:'Rule: No long dashes (—)',
  foundRuleEndings:'Rule: End posts on a statement, not a question',
  added:'Added. Edit or delete anything below.',
  addThese:'Add these',
  cancel:'Cancel',
  ruleDashes:'No long dashes (—)',
  ruleDashesNote:"Ownvoice won't use them",
  ruleEndings:'End posts on a statement',
  ruleEndingsNote:'Questions are still fine in replies',
  howIWrite:'How I write',
  howIWriteHint:'For example: short sentences, lowercase, blunt',
  neverSay:'Never say',
  neverSayHint:'One phrase per line',
  neverSayHelp:'One phrase per line. Any capitals; whole words only.',
  wipeElsewhere:'Wipe everything, under What Ownvoice read, deletes these too.',

  // What Ownvoice read (ReadsActivity).
  readsNote:'Each time you tap the bubble, Ownvoice notes the app, the time, what it helped with and whether ChatGPT saw the screen. Never any of your text. This list stays on this phone and each entry is deleted after 30 days.',
  wipe:'Wipe everything',
  wipeVoiceNote:'Wipe everything also deletes Your voice.',
  nothingRead:'Nothing read in the last 30 days.',
  today:'Today',

} as const;
