export const CHATGPT_TERMS = 'Uses your ChatGPT plan. OpenAI may change this at any time.';
export const technicalWords = /(?:gemini|gemma|\bnano\b|aicore|ml ?kit|\bllm\b|\bmodel\b|\/100|\/10\b|judge|slop|characters|\bprompt|\btokens?\b|on-device|gpt-\d|codex|openai api|responses|%|\bpercent\b|\(\d{3}\))/i;
export const plainReason = (reason: string) => !technicalWords.test(reason) && !/\d/.test(reason) && reason.trim().split(/\s+/).length <= 12;
export const words = {
  writeFirst:'Write a line or two first, and Ownvoice will help you polish it.',
  quickChecks:'These are quick checks to help you choose.',
  gettingReady:'Getting Ownvoice ready… this happens once.',
  writing:'Writing…',
  nothingYet:'Nothing to reply to yet',
  replyTitle:'Suggested replies',
  polishTitle:'Polish your message',
  postTitle:'Polish your post',
  readyReply:'Pick one to put in your message box. You send it yourself.',
  readyPolish:'Pick one to use instead of what you wrote. You send it yourself.',
  noField:'Tap into the message box first to use Insert, or copy one.',
  noCapture:'Nothing to read on this screen. Close this and tap the bubble again.',
  noReplies:'Couldn\'t come up with replies this time. Try again.',
  noVersions:'Couldn\'t polish that this time. Try again.',
  serviceOff:'Ownvoice is off. Use Copy instead.',
  fallback:'ChatGPT didn\'t answer. This phone wrote these instead.',
  chatgptFailed:'ChatGPT didn\'t answer this time.',
  tryAgain:'Try again',
  writeNew:'Write new ones',
  insert:'Insert',
  useThis:'Use this',
  copy:'Copy',
  why:'Why?',
  whyReply:'Why this reply',
  whyVersion:'Why this version',
  howItReads:'How it reads',
  checking:'Checking…',
  noChecks:'Couldn\'t run the other checks this time.',
  unsupported:"Sorry, Ownvoice doesn't work on this phone yet.",
  busy:'Your phone is busy. Try again in a moment.',
  batteryQuota:'Ownvoice needs a short break. Try again in a little while.',
  backgroundBlocked:'Open Ownvoice again and try once more.',
  noSpace:'Your phone needs a bit more free space to get Ownvoice ready.',
  requestTooLarge:'That chat is too long. Scroll to the latest messages and tap again.',
  systemUpdate:'Your phone needs an update first. Open Settings › System updates, then try again.',
  failed:'Something went wrong. Try again.',
  home:'Your writing helper. It stays on this phone.',
  permission:'On the next screen, tap Ownvoice, then switch on “Use Ownvoice”:',
  welcomeTitle:'Write replies that sound like you.',
  continueLabel:'Continue',
  permissionTitle:'Let Ownvoice see your chats, only when you tap',
  permissionSubtitle:'Android calls this “accessibility”. It’s the only way a helper can read a chat and fill in a message box for you.',
  promiseTap:'Reads only when you tap the bubble',
  promiseTapNote:'Never in the background',
  promisePhone:'Stays on this phone',
  promisePhoneNote:'Nothing is sent anywhere',
  promiseSend:'You always press Send',
  promiseSendNote:'Ownvoice never sends for you',
  switchRowApp:'Ownvoice',
  switchRowAction:'Use Ownvoice',
  on:'On',
  off:'Off',
  fullControl:'Android then asks to allow “full control”. It asks that of every helper like this one. Tap Allow.',
  turnOn:'Turn on',
  notNow:'Not now',
  switchGreyed:'Switch greyed out?',
  greyedHelp:'In App info, tap ⋮ at the top, then “Allow restricted settings”. Then come back and tap Turn on.',
  tryTitle:'Try it',
  tryInsert:'Tap the round bubble on the right, then Insert.',
  tryTurnOnFirst:'Turn Ownvoice on first, then come back here to try it.',
  tryDone:'That’s it. In your apps, read it over and press Send yourself.',
  practiceFriend:'Sam',
  practiceMessage1:'Are we still on for Saturday?',
  practiceMessage2:'I can bring the tent if you bring the stove.',
  practiceField:'Practice message',
  practiceNote:'It’s only practice: nothing here goes to anyone.',
  skip:'Skip',
  appsTitle:'Where should I help?',
  appsNote:'The bubble shows only in these apps. You can change this any time.',
  appsUnavailable:'Couldn’t find your apps. Try again.',
  tryAgain:'Try again',
  done:'Done',

} as const;
